# Setup
title:        Memegen
tagline:      
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Sira Horradarn, Chen Qiu

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
