# Setup
title:        Memegen
tagline:      
baseurl:      "sirahd.github.io/cse481a-18au-website"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Sira Horradarn, Chen Qiu

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
